Crown-Commercial-Service/digitalmarketplace-router

run.sh

Cloudfoundry have stopped using boot.sh in their static build pack. We
were calling it from run.sh, which was invoked as a custom start command
from the manifest. This broke things.
I've added the new default start command for the static build pack to
the end of the run.sh script.

Don't call boot.sh from run.sh

---

Makefile

Should be run once on each PaaS environment to provision the
CloudFront service.

Add make target to create cdn-route service

---

awslogs/awslogs.conf

We have renamed our log group from `nginx-json` to `router-json`
and now point our logs to the new group.

Use newly named `router-nginx` log group name

---

templates/_macros.j2

We don't nginx to pass this header on to later apps so instead
our apps will generate their own request ID instead of taking
the CloudFront one.

Drop Amazon Cloudfront Request ID header

---

templates/nginx.conf.j2

...in the hopes we can retrieve the fractional seconds with future work.
See https://github.com/alphagov/digitalmarketplace-docker-base/pull/22 for equivalent in that repo.

nginx: add `epochTime` to `log_format`

---

templates/nginx.conf.j2

nginx: unquote epochTime to ensure it's interpreted as a number

---

README.md

Adds a little more description about the scope of the router app. 
Notable by its absence from the list: caching 😿. I think we rely on PaaS's CDN defaults for client side caching headers - can anyone confirm if we have server side caching on PaaS or anywhere else?

Adds README info about the router app

---

.travis.yml
Makefile
README.md

Testing nginx changes locally is a bit annoying, especially if you just want to check for syntax errors. 
`make test-nginx` will spin up a new Docker container from your local changes and attempt to build and run nginx, outputting any config errors (from `nginx -t`). 
If the the config test is successful, the container is stopped and removed (ready for the next run). If there is a failure, the container is not removed and you can go in and investigate what's happened.
You can still follow the `docker-compose` instructions if you want to check more complex configuration/test different env vars/etc.

Makefile task for testing nginx config using Docker

---

templates/_macros.j2
templates/api.j2
templates/assets.j2
templates/nginx.conf.j2
templates/www.j2

We only want to allow sampling/debugging of requests from internal
(developer/GDS) IPs. If the request is from an external IP (i.e. a
normal user), strip out the two headers that indicate internal
debugging: X-B3-SAMPLED and X-B3-FLAGS.

Strip sampling headers

---

templates/api.j2

We want Notify to send us callbacks with information on the
success/failure of notification delivery so that we can act on the
outcome. We'll add a blueprint to the API attached at `/callbacks`, but
we need to open up those routes to external access so that the Notify
servers can post to it.
We will implement separate authentication on these routes for Notify to
use.
https://trello.com/c/vOAUDwnL/446

Allow external access to API callback route

---

templates/nginx.conf.j2

This is analogous to https://github.com/alphagov/digitalmarketplace-docker-base/pull/32
Using `X-B3-TraceId` request header instead of waiting for `DM-RequestId` response header (which we may or may not get back depending on whether the request actually reached an app) should more reliably give us an id.
This PR also adds the other zipkin headers to our log output.

nginx logging: switch to/output more zipkin header-derived information

---

templates/_macros.j2
templates/nginx.conf.j2

I think I've said enough about the implementation in the actual comments.
The purpose of this is to be able to gather profiling information
a) historically, to be able to look at aggregate statistics
b) during problematic performance spikes when we're not on-hand to probe them ourselves
without overwhelming ourselves with log volume. I've started off with 1/256 mostly because it's very straightforward to express in a regex, but that's tunable.

tracing: enable sampling mode for 1 in 256 requests, "randomly" driven by traceid

---

templates/_macros.j2

So yeah @katstevens was right when she spotted my logical error and I :hankey: :hankey: ed her. `$x_b3_sampled_value` will only be set to `0` if explicitly set by the requester or scrubbed by `$strip_trace_headers`. Otherwise it will be the empty string, which we also want to consider for random sampling.

random sampling: also consider empty strings as "unset" values of $x_b3_sampled_value

---

Makefile

We rarely want to actually run the `cf create-service`, far more often wanting `cf update-service`.
Also having the latter makes writing the manual page much less effort.

Makefile: add `update-cdn-route-service`, sharing config generation with `create-cdn-route-service`

---

Makefile
docker-compose.yml.example
templates/assets.j2

Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
Create a proxy URL for the new S3 bucket under our `assets.*` pattern.
Reliant on https://github.com/alphagov/digitalmarketplace-credentials/pull/151 being merged first.

Add reports S3 bucket to router nginx

---

static_files/maintenance.html
static_files/too_many_requests.html

Trello: https://trello.com/c/bZRTXILM/178-update-maintenance-page-static-html-on-router-app-to-include-new-header-styling
The 'Planned maintenance' and the 429 'Too Many Requests' static pages had the old header and footer.
- Drops IE8 support (if IE8 users are looking at these pages then they probably have bigger problems to worry about than spacing)
- Removes a bunch of javascript that didn't seem useful (perhaps you, the reviewer, know what it was for)
- Uses the `https://assets.publishing.service.gov.uk/static/govuk-template.css` stylesheet for base styles
- Includes in the `<style>` tag some selected highlights from the Buyer FE's `application.css` file (removing stuff like forms, tables, buttons etc that aren't rendered on these pages). 
- I did the maintenance page first, then …

Update maintenance and 429 static pages

---

Dockerfile

Updates nginx to latest version of nginx 1.14 (currently 1.14.1). Nginx 1.14 is the stable branch, there is also a mainline branch, 1.15.
Closes https://trello.com/c/zBUjwx0o
Nginx [changelog](https://nginx.org/en/CHANGES-1.14) does not indicate any breaking changes, and `make test-nginx` reported no issues with the configuration file.

Update nginx to latest stable version

---

Makefile
scripts/render-template.py
templates/api.j2
templates/assets.j2
templates/www.j2

https://trello.com/c/ZniGEuve
This ensures that the target is interpreted as a URI and so has the *normalized* path of the incoming request applied to it to generate the onwards path, notably having performed slash merging.
This does however mean that we can't use nginx "variables" for these target urls because those are too dynamic and opaque to nginx's configuration system for it to be able to make decisions about behaviour based on their values. fortunately we can of course still use jinja variables.
The idea with the `ensure_trailing_slash` filter is I didn't want to burden the vars file with those editing it needing to know about this specific necessity for there to be/not to be a trailing slash included in this variable. And other places using this variable might have other …

proxy_pass: make sure, in most cases, target url is specified with a trailing slash

---

templates/www.j2

Disallow access to metrics through public url
* Add rule to nginx denying access to any endpoint ending in /metrics from public urls

322-move-metrics-to-metrics-and-expose

---

templates/api.j2
templates/assets.j2
templates/www.j2

We need to define our urls as variables and pass these to proxy pass to ensure the dns lookup is periodically expired.
We have seen 504 errors when the ips of our s3 buckets are changed because the DNS resolution is never expired and always points to the ip looked up when the papp is started.
> domain names statically configured in config are only looked up once on startup (or configuration reload).
https://forum.nginx.org/read.php?2,215830,215832#msg-215832
> Setting proxy_pass to a variable forces re-resolution of the DNS names, because Nginx treats variables differently to static configuration
https://serverfault.com/a/593003
These variables must be set _outside_ the location block:
https://serverfault.com/questions/240476/how-to-force-nginx-to-resolve-dns-of-a-dynamic-hostname-everytim …

592-504-errors-on-production-nginx-dns

---

templates/assets.j2

We want to serve a blank favicon on this domain as we cannot guarantee the content it will appear above (service
documents, user uploaded pdfs etc.). The blank favicon stops 404s propagating past this point.
Uses:
http://nginx.org/en/docs/http/ngx_http_empty_gif_module.html

376-the-404-chain-reaction-browsers-requesting-favicons-from-our-assets-host

---

Makefile
README.md
templates/nginx.conf.j2
templates/www.j2

Part of the work to make load testing easier (Trello: https://trello.com/c/tFiYL9vk/379-load-test-the-supplier-account-creation-journey).
Utilises the new `DM_RATE_LIMITING_ENABLED` var from the router's PaaS manifest (see https://github.com/alphagov/digitalmarketplace-aws/pull/499) to optionally include the rate limiting config.

Include rate limit config if option set

---

Makefile
templates/nginx.conf.j2
templates/www.j2

Check that `DM_RATE_LIMITING_ENABLED` is set to 'enabled' or 'disabled', rather than relying on the presence or absence of the variable (which confuses Jinja) (and confuses me).

Set rate limit toggle to a value

---

templates/assets.j2

Force assets favicon mime type to image/x-icon
It looks like our other favicon has it's mime-type set to `image/x-icon`
We should set the assets one to this for consistency
https://trello.com/c/ZWvPcWdx/395-force-assets-favicon-mime-type-to-image-x-icon

395-force-assets-favicon-mime-type-to-image-x-icon

---

templates/api.j2
templates/www.j2

https://trello.com/c/H53K45It
This is needed because internal ("private") PaaS routes are load-balanced simply on a DNS trick and our blue-green deployment procedure may make an instance disappear at any time with little notice.
While I'd love to be able to test this without merging, that slightly defeats the point because it's a problem with deployment & releasing that this is trying to fix, and we need to go through a proper release cycle to see if it works.
Note I've added this rule for connections to our frontend apps too even though we don't yet use internal routes for them - this is because I anticipate someone trying to switch them too sooner or later and I'd rather they don't have to rediscover this problem from scratch then.

local proxying: set a default resolver ttl of 10s

---

templates/api.j2
templates/www.j2

Reverts alphagov/digitalmarketplace-router#54
This change is now pointless - the approach won't work because of fun nginx things as described in https://github.com/DmitryFillo/nginx-proxy-pitfalls

Revert "local proxying: set a default resolver ttl of 10s"

---

templates/api.j2

https://trello.com/c/H53K45It
So it looks like the way to actually solve this is go Full Ben.

api proxying: switch to using variable/regex trick to encourage nginx to refresh its dns lookups

---

templates/nginx.conf.j2

https://trello.com/c/bzsaiTQ1
Without this it's hard to identify when a request was "slow" simply because it was uploading a 5MB file.

logging: include requestSize

---

templates/nginx.conf.j2

...which is actually most requests - we can't let possibly-unset values be used unquoted in the json otherwise they'll break it.
Also enable `escape=json` option for `log_format`
https://trello.com/c/bzsaiTQ1

requestSize logging: handle unset $content_length values 

---

templates/nginx.conf.j2

https://trello.com/c/bzsaiTQ1
Sorry to keep screwing with this but we really should be a bit safer here seeing as it originates as an http header.

requestSize logging: use a regex map instead to ensure we only inject digits into the log json

---

templates/assets.j2

Trello: https://trello.com/c/okOq2o7m/655-505-error-for-malformed-s3-document-url
This status code returns when a malformed S3 document URL is requested (eg containing spaces, colons). We'll still get a 5xx alert but this fix should at least show a nice 404 error page to the user instead of an ugly XML error response (like the one on the ticket).

Serve a 404 error page when 505 error received from AWS

---

templates/nginx.conf.j2

Because visibility.
Note that these can have multiple comma separated values corresponding to multiple attempts.

access logs: add $upstream_connect_time, $upstream_header_time, $upstream_response_time

---

templates/www.j2

Make frontend apps proxy_passes use regex and variable
This means that the url will be re resolved not cached for the life of the router app and that the urls will have double slashes squashed.
https://trello.com/c/HpOQ0y5V/768-p3-instability-09-05-2019-04-05am-and-06-07am
See https://github.com/alphagov/digitalmarketplace-router/pull/46 for more info

768-p3-instability-09-05-2019-04-05am-and-06-07am

---

awslogs/run.sh
supervisord.conf

https://trello.com/c/PyDaRXEj
Analogous to https://github.com/alphagov/digitalmarketplace-docker-base/pull/56/
We will never make this perfect as it's possible for an instance to have a significant number of concurrent or queued connections and only a 10s grace period given by bosh in which to clear that backlog. so make sure daemons are given graceful shutdown signals so they can get on with doing that backlog-clearing. Ensure awslogs daemon doesn't shut down at all until the last second so we have a good shot at getting logs of all handled requests.

supervisord: attempt more graceful shutdown procedure through better use of signals

---

.dockerignore
Dockerfile
nginx-prometheus-exporter.sh
nginx.sh
supervisord.conf
templates/metrics.j2

https://trello.com/c/wkDN6HHk/
This requires us to set up the "status stub", made only accessible from within the host, the `nginx-prometheus-exporter` process itself (for polling that status stub) and a `proxy_pass` rule to allow requests to `/_metrics` to be _apparently_ served by our nginx from port 80. It might seem nicer for these nginx settings to live in their own site config file, but that's tricky because we already have the healthcheck set as the default port 80 "server", so rather have to piggyback on that.
~The endpoint is set up like the healthcheck, only visible when accessed "raw" and not through one of the configured hostnames. I _think_ our "master" exporter _should_ be able to access this endpoint, but not 100% certain.~

add prometheus metric exporter

---

static_files/maintenance.html

trello: https://trello.com/c/8uz6Nqob/60-maintenance-mode-doesnt-load-static-resources
Quick and dirty approach by embedding the CSS in the maintenance HTML and loading images and fonts from the CDN gov.uk frontend is dumped.

Maintenance assets from cdn

---

scripts/render-template.py

This work disables autoescaping on jinja templates. We're confident we can do this because these templates have no user input, and we're worried about the impact of autoescaping templates that generate nginx configurations
[Ticket](https://trello.com/c/H2ubPYqz/306-enable-autoescape-on-jinja-templates)

Disable autoescape for 'j2' templates

---

templates/nginx.conf.j2

https://trello.com/c/2k1WIjxX
Nginx defaults to downgrading outbound connections to http 1.0. Forcing it to use http 1.1 should allow paas to do some keepalive magick. S3, which we also proxy to, should be able to handle this too.
Tested & works on staging.

set proxy_http_version to 1.1

---

Dockerfile
Makefile
nginx.sh
templates/nginx.conf.j2

https://trello.com/c/1ch9wfEa
There isn't a practical way of disabling gzip for `text/html` in nginx, and the sensitive nature of some of the html means we probably don't want compression there due to e.g. BREACH concerns. instead we will perform gzipping in the applications where we can have a little more control.
Tested and works on preview alongside https://github.com/alphagov/digitalmarketplace-docker-base/pull/64 but we need to wait for that to be merged and propagated to apps before merging this.

disable gzip at toplevel

---

Makefile

Ticket: https://trello.com/c/cwjzIU8U/87-stop-search-api-from-using-port-5001

Change the default port for the search api

---

.travis.yml

https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
No libraries bumped

Enable Travis checks for Python 3.7 and 3.8

---

.travis.yml

We don't have any Python tests in this repo, so for a more accurate reflection of our coverage, let's remove it from the Travis setup and use the `minimal` base image instead (which still includes `make`, `Docker` etc). Bonus: it should run quicker as well...
See https://docs.travis-ci.com/user/languages/minimal-and-generic/#minimal

Run Travis tests with basic image instead of Python

---

nginx.sh

https://trello.com/c/j1kYVu3a/1303-implement-multi-maintenance-mode
This new mode would be used following a DB restore, where we still want to block access to the FE apps, but allow Jenkins to access the APIs for jobs that reindex the restored data.
We'll need to change the corresponding Jenkins job and script to allow the new value to be set there, but if this is merged in isolation, a developer could set the `DM_MODE` environment variable using the CloudFoundry CLI.

Add recovery mode to enable API requests

---

Dockerfile
nginx-prometheus-exporter.sh

We've had issues where the router app metrics have not been available because the nginx-prometheus-exporter app has started before the NGINX stub_status page is available, and exited with an error.
This commit uses the command line argument `-nginx.retries int` to get nginx-prometheus-exporter to retry a couple of times before exiting with an error.
3 seems like as good a number of retries as any.

Use nginx.retries to ask nginx-prometheus-exporter to wait for NGINX

---

docker-compose.yml.example
templates/www.j2

https://trello.com/c/qmR9Qvb6/1886-robotstxt-raises-404
For some reason the prefix match wasn't working with the location block and visiting /robots.txt was resulting in a 404. This PR changes the match to be an exact one, which seems to fix ix the issue.

Fix robots.txt

---

Makefile
supervisord.conf

We're not currently seeing all the log files in Splunk that we do on Kibana. We need have NGINX access logs in stdout of our PaaS app, so it will appear in `cf logs` and be forwarded to Splunk.
This commit copies the method used in alphagov/digitalmarketplace-docker-base#74, adding a process that continually echoes the contents of the log file to stdout. We need to keep the logfile so that awslogs can keep forwarding to CloudWatch.

Add supervisord process to forward NGINX logs to stdout

---

templates/nginx.conf.j2

Ticket: https://trello.com/c/XDAj8wiB/2063-large-number-of-buyer-frontend-due-to-high-traffic-on-2020-11-05
Discussed with @bjgill this seemed like a good level for now. Ideally in the future we should scale the rate limit with the number of router apps.

Reduce rate limit for requests to 15r/s

---

.dependabot/config.yml

Our router app is based off the official nginx Docker image, but we don't track the nginx version closely so we get out-of-date.
Enable dependabot checking so we can keep our router app up-to-date with its dependencies, and make sure we're aware of any vulnerabilities.
https://trello.com/c/UeAD1ZYq/1407-1-add-digitalmarketplace-router-docker-image-to-dependabot

Enable dependabot version checking on the base nginx image

---

templates/nginx.conf.j2

https://trello.com/c/xoQsBBAd
We have a scraper that hits us with a very large amount of traffic in a short space of time every day. Buyer-frontend is unable to cope, and gets terminated. See the linked Trello ticket for more detailed information.
The scraper is currently just under our rate limit. So try reducing the rate limit. Hopefully, they are nice and will start limiting their request rate to one we can handle. If not, we may need to try more extreme measures.
I propose lowering the rate limit to 5 requests/second/instance (30 requests/second overall). We should review our logs after a week to see what impact this had on users and on the scraper.

Reduce rate limit to 5 requests/second/instance

---

templates/nginx.conf.j2

The recent ITHC identified that we were missing some HTTP response headers that they would recommend including as best practice to prevent the risk of cross site scripting and other code execution attacks
`Content-Security-Policy` aims to mitigate XSS attacks by allowing the server administrator to specify domains the browser is allowed to load and execute resources from[[1]]. 
This policy allows:
1. All resources from the domain the page is served on
2. Scripts from our domain, inline scripts and from Google Analytics
3. Images from our domain and inline SVGs using a `data:` url
4. Scripts to load URLs on our domain and for Google Analytics
https://trello.com/c/q6d3d6vP/884-3-address-ithc-issue-612-missing-http-security-headers
[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Add Content-Security-Policy header

---

templates/nginx.conf.j2

In a blog post **'Privacy, sustainability and the importance of “and”'**[[1]], Google announced their new approach to audience-led display ads in the absence of third party cookies.
The blog post and the web.dev post[[2]] have more details, but in summary Google will use aggregated browsing history data to generate cohorts of people with similar browsing behaviour. Browsers then use this cohort model and apply it to the local browsing history to determine which cohort the user most likely fits into. This is designed to preserve the user's privacy because their browsing history isn't sent off to another company to be analysed - the cohort assignment happens on their machine.
However, there are still privacy concerns[[3]] about how the cohort model is trained and how Google will exclude …

Opt out of Google Federated Learning of Cohorts computation

---

templates/nginx.conf.j2
templates/www.j2

Trello: https://trello.com/c/wW4w1XQZ
We've got a scraper who attempts to scrape 1500-2000 pages in the space of 2 minutes on a regular basis. We're almost able to cope with this, but are still getting the odd 502 response that suggests that the DMp is unable to cope with this level of traffic 100% reliably.
So halve the permitted rate limit and also the allowed burst. The DMp should easily be able to handle the scraper's current level of traffic given this rate limit. We'll need to monitor to check whether this affects any other users.
We also need to take other steps to make the DMp more able to cope with this sort of traffic. Reducing the rate limit should buy us the time to make those improvements.
**If you are the scraper in question**: please [contact …

Reduce request rate limits and allowed burst

---

templates/nginx.conf.j2

Currently, admins are unable to view framework agreements. We think this is because the Content Security Policy does not allow our assets subdomain, which we embed to display the agreements. This was introduced in https://github.com/alphagov/digitalmarketplace-router/pull/106.
So add our assets subdomain to our CSP.
I'll merge this to Preview to test whether it fixes our problems.

Add assets subdomain to CSP

---

templates/nginx.conf.j2

https://govuk.zendesk.com/agent/tickets/4533739
We can't currently embed PDF from our assets domain on Chrome. This should work because we've set object-src, which controls embedding (https://github.com/alphagov/digitalmarketplace-router/pull/110).
However, Chrome seems to have a bug that makes it look at frame-src instead (https://stackoverflow.com/questions/57826510/chrome-shows-frame-src-error-even-if-using-object). So we need to provide frame-src.

Add assets subdomain to CSP for Chrome

---

.dockerignore
Dockerfile
supervisor_stdout.py
supervisord.conf

Use a fork of https://github.com/coderanger/supervisor-stdout to forward logs from application to stdout.
The previous solution was not resilient to log rotation, so we would lose logs after the app had been running for a while. This new solution should hopefully not have the same issue.
Very similar to https://github.com/alphagov/digitalmarketplace-docker-base/pull/80
https://trello.com/c/QawDH4Jz/2207-what-happened-to-the-nginx-access-logs

Add supervisor_stdout

---

.github/workflows/test.yml
Dockerfile

https://trello.com/c/bsrCIPPZ/214-upgrade-the-router-to-use-python-v39
With the latest update to nginx, we can now use Python 3.9 in the router.
This is the last app using Python 3.7 so after this has been merged, all apps will be using Python >= 3.8

Upgrade to python 3.9
